### ISSUE TITLE
Published version is 0.1.4 on go.pkg

### ISSUE THREAD

**Issue by RichardLindhout** [gertd/go-pluralize#9]
Can you please do a Github 0.1.4 release?

pkg.go.dev thinks there is a version 0.1.4
https://pkg.go.dev/github.com/gertd/go-pluralize@v0.1.4?tab=doc

https://github.com/web-ridge/gqlgen-sqlboiler/issues/11

**Comment by RichardLindhout** [comment]
https://github.com/web-ridge/sqlboiler-graphql-schema/issues/5

**Comment by RichardLindhout** [comment]
https://github.com/web-ridge/gqlgen-sqlboiler/issues/11

**Comment by gertd** [comment]
Released v0.1.6, sorry for not seeing this earlier!

**Comment by RichardLindhout** [comment]
No problem! Amazing library btw. Keep up the good work. It's even used by Google :-D  --> https://github.com/gertd/go-pluralize/issues/8
